config/routes.rb
Rails.application.routes.draw do

  resources :societies
  resources :user_details
  mount Spree::Core::Engine, :at => '/'

Spree::Core::Engine.add_routes do
  namespace :api, defaults: {format: 'json'} do
    resource :users do
      post :sign_up
      post :sign_in
    end
  end
end

namespace :admin do 
	 resources :societies
end

end

app/models/society.rb
class Society < ActiveRecord::Base
end

app/models/user_detail.rb
class UserDetail < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
end

app/controllers/societies_controller.rb
class SocietiesController < ApplicationController
  before_action :set_society, only: [:show, :edit, :update, :destroy]

  # GET /societies
  # GET /societies.json
  def index
    @societies = Society.all
  end

  # GET /societies/1
  # GET /societies/1.json
  def show
  end

  # GET /societies/new
  def new
    @society = Society.new
  end

  # GET /societies/1/edit
  def edit
  end

  # POST /societies
  # POST /societies.json
  def create
    @society = Society.new(society_params)

    respond_to do |format|
      if @society.save
        format.html { redirect_to @society, notice: 'Society was successfully created.' }
        format.json { render :show, status: :created, location: @society }
      else
        format.html { render :new }
        format.json { render json: @society.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /societies/1
  # PATCH/PUT /societies/1.json
  def update
    respond_to do |format|
      if @society.update(society_params)
        format.html { redirect_to @society, notice: 'Society was successfully updated.' }
        format.json { render :show, status: :ok, location: @society }
      else
        format.html { render :edit }
        format.json { render json: @society.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /societies/1
  # DELETE /societies/1.json
  def destroy
    @society.destroy
    respond_to do |format|
      format.html { redirect_to societies_url, notice: 'Society was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_society
      @society = Society.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def society_params
      params.require(:society).permit(:name, :url, :building_number, :address, :area, :postcode, :city, :active, :IsDelete)
    end
end

app/controllers/spree/api/users_controller_decorator.rb
module Spree
  module Api

    UsersController.class_eval do

      before_action :authenticate_user, :except => [:sign_up, :sign_in]

      def sign_up

        @user = Spree::User.find_by_email(params[:user][:email])

        if @user.present?
          render "spree/api/users/user_exists", :status => 401 and return
        end

        @user = Spree::User.new(user_params)
        if !@user.save
          unauthorized
          return
        end
        @user.generate_spree_api_key!
      end

      def sign_in
        @user = Spree::User.find_by_email(params[:user][:email])
        if !@user.present? || !@user.valid_password?(params[:user][:password])
          unauthorized
          return
        end
        @user.generate_spree_api_key! if @user.spree_api_key.blank?
      end


      def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
      end

    end
  end
end

app/controllers/user_details_controller.rb
class UserDetailsController < ApplicationController
  before_action :set_user_detail, only: [:show, :edit, :update, :destroy]

  # GET /user_details
  # GET /user_details.json
  def index
    @user_details = UserDetail.all
  end

  # GET /user_details/1
  # GET /user_details/1.json
  def show
  end

  # GET /user_details/new
  def new
    @user_detail = UserDetail.new
  end

  # GET /user_details/1/edit
  def edit
  end

  # POST /user_details
  # POST /user_details.json
  def create
    @user_detail = UserDetail.new(user_detail_params)

    respond_to do |format|
      if @user_detail.save
        format.html { redirect_to @user_detail, notice: 'User detail was successfully created.' }
        format.json { render :show, status: :created, location: @user_detail }
      else
        format.html { render :new }
        format.json { render json: @user_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_details/1
  # PATCH/PUT /user_details/1.json
  def update
    respond_to do |format|
      if @user_detail.update(user_detail_params)
        format.html { redirect_to @user_detail, notice: 'User detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_detail }
      else
        format.html { render :edit }
        format.json { render json: @user_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_details/1
  # DELETE /user_details/1.json
  def destroy
    @user_detail.destroy
    respond_to do |format|
      format.html { redirect_to user_details_url, notice: 'User detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_detail
      @user_detail = UserDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_detail_params
      params.require(:user_detail).permit(:id_user, :firstname, :lastname, :telephone, :mobile, :number_of_family_members, :number_of_servants, :vehicle_number, :pets, :intercom_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/societies_helper.rb
module SocietiesHelper
end

app/helpers/user_details_helper.rb
module UserDetailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Storejust</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/societies/_form.html.erb
<%= form_for(@society) do |f| %>
  <% if @society.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@society.errors.count, "error") %> prohibited this society from being saved:</h2>

      <ul>
      <% @society.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :building_number %><br>
    <%= f.text_field :building_number %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :area %><br>
    <%= f.text_field :area %>
  </div>
  <div class="field">
    <%= f.label :postcode %><br>
    <%= f.number_field :postcode %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.number_field :active %>
  </div>
  <div class="field">
    <%= f.label :IsDelete %><br>
    <%= f.number_field :IsDelete %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/societies/edit.html.erb
<h1>Editing Society</h1>

<%= render 'form' %>

<%= link_to 'Show', @society %> |
<%= link_to 'Back', societies_path %>

app/views/societies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Societies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Building number</th>
      <th>Address</th>
      <th>Area</th>
      <th>Postcode</th>
      <th>City</th>
      <th>Active</th>
      <th>Isdelete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @societies.each do |society| %>
      <tr>
        <td><%= society.name %></td>
        <td><%= society.url %></td>
        <td><%= society.building_number %></td>
        <td><%= society.address %></td>
        <td><%= society.area %></td>
        <td><%= society.postcode %></td>
        <td><%= society.city %></td>
        <td><%= society.active %></td>
        <td><%= society.IsDelete %></td>
        <td><%= link_to 'Show', society %></td>
        <td><%= link_to 'Edit', edit_society_path(society) %></td>
        <td><%= link_to 'Destroy', society, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Society', new_society_path %>

app/views/societies/new.html.erb
<h1>New Society</h1>

<%= render 'form' %>

<%= link_to 'Back', societies_path %>

app/views/societies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @society.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @society.url %>
</p>

<p>
  <strong>Building number:</strong>
  <%= @society.building_number %>
</p>

<p>
  <strong>Address:</strong>
  <%= @society.address %>
</p>

<p>
  <strong>Area:</strong>
  <%= @society.area %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @society.postcode %>
</p>

<p>
  <strong>City:</strong>
  <%= @society.city %>
</p>

<p>
  <strong>Active:</strong>
  <%= @society.active %>
</p>

<p>
  <strong>Isdelete:</strong>
  <%= @society.IsDelete %>
</p>

<%= link_to 'Edit', edit_society_path(@society) %> |
<%= link_to 'Back', societies_path %>

app/views/user_details/_form.html.erb
<%= form_for(@user_detail) do |f| %>
  <% if @user_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_detail.errors.count, "error") %> prohibited this user_detail from being saved:</h2>

      <ul>
      <% @user_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_user %><br>
    <%= f.number_field :id_user %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br>
    <%= f.number_field :telephone %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.number_field :mobile %>
  </div>
  <div class="field">
    <%= f.label :number_of_family_members %><br>
    <%= f.number_field :number_of_family_members %>
  </div>
  <div class="field">
    <%= f.label :number_of_servants %><br>
    <%= f.number_field :number_of_servants %>
  </div>
  <div class="field">
    <%= f.label :vehicle_number %><br>
    <%= f.text_field :vehicle_number %>
  </div>
  <div class="field">
    <%= f.label :pets %><br>
    <%= f.number_field :pets %>
  </div>
  <div class="field">
    <%= f.label :intercom_number %><br>
    <%= f.number_field :intercom_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_details/edit.html.erb
<h1>Editing User Detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_detail %> |
<%= link_to 'Back', user_details_path %>

app/views/user_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Details</h1>

<table>
  <thead>
    <tr>
      <th>Id user</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Telephone</th>
      <th>Mobile</th>
      <th>Number of family members</th>
      <th>Number of servants</th>
      <th>Vehicle number</th>
      <th>Pets</th>
      <th>Intercom number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_details.each do |user_detail| %>
      <tr>
        <td><%= user_detail.id_user %></td>
        <td><%= user_detail.firstname %></td>
        <td><%= user_detail.lastname %></td>
        <td><%= user_detail.telephone %></td>
        <td><%= user_detail.mobile %></td>
        <td><%= user_detail.number_of_family_members %></td>
        <td><%= user_detail.number_of_servants %></td>
        <td><%= user_detail.vehicle_number %></td>
        <td><%= user_detail.pets %></td>
        <td><%= user_detail.intercom_number %></td>
        <td><%= link_to 'Show', user_detail %></td>
        <td><%= link_to 'Edit', edit_user_detail_path(user_detail) %></td>
        <td><%= link_to 'Destroy', user_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User detail', new_user_detail_path %>

app/views/user_details/new.html.erb
<h1>New User Detail</h1>

<%= render 'form' %>

<%= link_to 'Back', user_details_path %>

app/views/user_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id user:</strong>
  <%= @user_detail.id_user %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @user_detail.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user_detail.lastname %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @user_detail.telephone %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @user_detail.mobile %>
</p>

<p>
  <strong>Number of family members:</strong>
  <%= @user_detail.number_of_family_members %>
</p>

<p>
  <strong>Number of servants:</strong>
  <%= @user_detail.number_of_servants %>
</p>

<p>
  <strong>Vehicle number:</strong>
  <%= @user_detail.vehicle_number %>
</p>

<p>
  <strong>Pets:</strong>
  <%= @user_detail.pets %>
</p>

<p>
  <strong>Intercom number:</strong>
  <%= @user_detail.intercom_number %>
</p>

<%= link_to 'Edit', edit_user_detail_path(@user_detail) %> |
<%= link_to 'Back', user_details_path %>